### ISSUE TITLE
Alternative?

### ISSUE THREAD

**Issue by log69** [palant/suspendbackgroundtabs#2]
Hi Wladimir, suspendbackgroundtabs was a great Firefox extension saving huge CPU resources eaten by the badly designed websites. It saved battery for notebooks.

Discontinuing it, what other method you are using or you can recommend to achieve the same results for Firefox? Stopping background scripts on inactive tabs?

Thanks.

**Comment by palant** [comment]
Anybody is free to continue working on this extension, it's merely that I am not doing it any more. I'm not aware of any alternatives other than not using badly designed websites or tell their owners about the CPU hogging issues. This doesn't mean that there aren't any comparable extensions, I'm merely not aware of any.
